version: '3.8'

services:
  db_wb:
    image: postgres:15-alpine
    container_name: wbapi_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: wb_tariffs
    ports:
      - "5432:5432"
    volumes:
      - wb_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - wb_network

  backend:
    build: ./backend
    container_name: wbapi_backend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      db_wb:
        condition: service_healthy
    networks:
      - wb_network

volumes:
  wb_postgres_data:

networks:
  wb_network:
    driver: bridge
